version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: outage-db-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd2024!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: outage-api-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=OutageDb;User Id=sa;Password=P@ssw0rd2024!;TrustServerCertificate=True;MultipleActiveResultSets=true
    ports:
      - "8080:8080"
    depends_on:
      - mssql

volumes:
  mssqldata:
